name = "kwagies"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_TELEMETRY_DISABLED = "1"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
